/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'
import { Route as CapabilitiesToolRoomRouteImport } from './routes/capabilities.tool-room'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InfrastructureIndexRouteImport } from './routes/infrastructure.index'
import { Route as InfrastructureMachineryRouteImport } from './routes/infrastructure.machinery'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as QualityCertificationsRouteImport } from './routes/quality.certifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AboutRoute,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesToolRoomRoute = CapabilitiesToolRoomRouteImport.update({
  id: '/capabilities/tool-room',
  path: '/capabilities/tool-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureIndexRoute = InfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureMachineryRoute = InfrastructureMachineryRouteImport.update({
  id: '/infrastructure/machinery',
  path: '/infrastructure/machinery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityCertificationsRoute = QualityCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => QualityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/gallery': typeof GalleryRoute
  '/performance': typeof PerformanceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/terms': typeof TermsRoute
  '/about/team': typeof AboutTeamRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/tool-room': typeof CapabilitiesToolRoomRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/infrastructure/machinery': typeof InfrastructureMachineryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/quality/certifications': typeof QualityCertificationsRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/gallery': typeof GalleryRoute
  '/performance': typeof PerformanceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/terms': typeof TermsRoute
  '/about/team': typeof AboutTeamRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/tool-room': typeof CapabilitiesToolRoomRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/infrastructure/machinery': typeof InfrastructureMachineryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/quality/certifications': typeof QualityCertificationsRoute
  '/capabilities': typeof CapabilitiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/infrastructure': typeof InfrastructureIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/gallery': typeof GalleryRoute
  '/performance': typeof PerformanceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/terms': typeof TermsRoute
  '/about/team': typeof AboutTeamRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/tool-room': typeof CapabilitiesToolRoomRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/infrastructure/machinery': typeof InfrastructureMachineryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/quality/certifications': typeof QualityCertificationsRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/gallery'
    | '/performance'
    | '/privacy-policy'
    | '/quality'
    | '/request-quote'
    | '/terms'
    | '/about/team'
    | '/capabilities/$slug'
    | '/capabilities/tool-room'
    | '/industries/$slug'
    | '/infrastructure/machinery'
    | '/products/$slug'
    | '/quality/certifications'
    | '/capabilities/'
    | '/industries/'
    | '/infrastructure/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/gallery'
    | '/performance'
    | '/privacy-policy'
    | '/quality'
    | '/request-quote'
    | '/terms'
    | '/about/team'
    | '/capabilities/$slug'
    | '/capabilities/tool-room'
    | '/industries/$slug'
    | '/infrastructure/machinery'
    | '/products/$slug'
    | '/quality/certifications'
    | '/capabilities'
    | '/industries'
    | '/infrastructure'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/gallery'
    | '/performance'
    | '/privacy-policy'
    | '/quality'
    | '/request-quote'
    | '/terms'
    | '/about/team'
    | '/capabilities/$slug'
    | '/capabilities/tool-room'
    | '/industries/$slug'
    | '/infrastructure/machinery'
    | '/products/$slug'
    | '/quality/certifications'
    | '/capabilities/'
    | '/industries/'
    | '/infrastructure/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  GalleryRoute: typeof GalleryRoute
  PerformanceRoute: typeof PerformanceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QualityRoute: typeof QualityRouteWithChildren
  RequestQuoteRoute: typeof RequestQuoteRoute
  TermsRoute: typeof TermsRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  CapabilitiesToolRoomRoute: typeof CapabilitiesToolRoomRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InfrastructureMachineryRoute: typeof InfrastructureMachineryRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InfrastructureIndexRoute: typeof InfrastructureIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof AboutRoute
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/tool-room': {
      id: '/capabilities/tool-room'
      path: '/capabilities/tool-room'
      fullPath: '/capabilities/tool-room'
      preLoaderRoute: typeof CapabilitiesToolRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/': {
      id: '/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof InfrastructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/machinery': {
      id: '/infrastructure/machinery'
      path: '/infrastructure/machinery'
      fullPath: '/infrastructure/machinery'
      preLoaderRoute: typeof InfrastructureMachineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/certifications': {
      id: '/quality/certifications'
      path: '/certifications'
      fullPath: '/quality/certifications'
      preLoaderRoute: typeof QualityCertificationsRouteImport
      parentRoute: typeof QualityRoute
    }
  }
}

interface AboutRouteChildren {
  AboutTeamRoute: typeof AboutTeamRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutTeamRoute: AboutTeamRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface QualityRouteChildren {
  QualityCertificationsRoute: typeof QualityCertificationsRoute
}

const QualityRouteChildren: QualityRouteChildren = {
  QualityCertificationsRoute: QualityCertificationsRoute,
}

const QualityRouteWithChildren =
  QualityRoute._addFileChildren(QualityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  GalleryRoute: GalleryRoute,
  PerformanceRoute: PerformanceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QualityRoute: QualityRouteWithChildren,
  RequestQuoteRoute: RequestQuoteRoute,
  TermsRoute: TermsRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  CapabilitiesToolRoomRoute: CapabilitiesToolRoomRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InfrastructureMachineryRoute: InfrastructureMachineryRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InfrastructureIndexRoute: InfrastructureIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
